### ISSUE TITLE
Dual Base Image

### ISSUE THREAD

**Issue by prvst** [BioContainers/specs#70]
With the oficial release of Docker for Windows we now have to discuss the possibility / necessity of having a dual base image; one based on the latest Ubuntu LTS (like we already do), and the other based on Microsoft Windows. Do you guys, @BioContainers/contributors,  think this is necessary ?

**Comment by ypriverol** [comment]
Is possible to run this into linux or not yet. If someone from the community has a Windows machine would be great to release a couple of contianers in Windows MaxQuant Skyline? @prvst

**Comment by prvst** [comment]
I have no idea how those windows images works, but I would not rush too much into proprietary and closed-software for those containers.

**Comment by pcm32** [comment]
My understanding is that windows docker containers run only on top of
windows machines, so you need a licenced windows installation.

**Comment by prvst** [comment]
yes, thats also true

**Comment by ypriverol** [comment]
That is not true docker already have the official channed of Microssoft with their based containers like the Ubuntu for Linux (official channel of Microsoft https://hub.docker.com/u/microsoft/). We can based our image on top of the windows image. The only problem is that you need a Windows machine to deploy, test and deploy those containers because they are not cross-platform. This is what I understand.

**Comment by prvst** [comment]
hum, yes, @ypriverol is right, but I think that's what @pcm32 was talking about it. And it must be a Windows 10 machine. Here at the University they only license Windows 7.

**Comment by pcm32** [comment]
Yes, that is what I meant, that you need a windows machine to run those containers.

**Comment by bgruening** [comment]
I don't think it is needed and we should push OpenSource as much as possible not the other way around :)

**Comment by ypriverol** [comment]
This issue can be closed.
